# -*- coding: utf-8 -*-
"""UntitledHello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EoX14FYwWFRSrGRavvFAGc5d5h2Q3Cjm
"""

# Why do we live?

# Just to suffer?